export const data = [
  {
    id: 1,
    title: "Long sleeve Jacket",
    description:
      "Add a touch of casual style to your wardrobe with these canvas flats. They are lightweight and comfortable for all-day wear. Available in various colors and sizes.",
    colors: ["#336600", "#993300"],
    imghover: "/images/img-hover4.jpg",
    img: "images/img4.jpg",
    images: ["/images/img1.jpg", "/images/img2.jpg", "/images/img3.jpg"],
    company: "CasualChic",
    price: 200,
    oldprice: 220,
    category: "shoes",
    type: "Flats",
    rating: 4.5,
    stock: 90,
    gender: "man",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 2,
    title: "Long sleeve Jacket",
    description:
      "Add a touch of casual style to your wardrobe with these canvas flats. They are lightweight and comfortable for all-day wear. Available in various colors and sizes.",
    colors: ["#336600", "#993300"],
    imghover: "/images/img-hover1.jpg",
    img: "images/img1.jpg",
    images: ["/images/img1.jpg", "/images/img2.jpg", "/images/img3.jpg"],
    company: "CasualChic",
    price: 200,
    oldprice: 220,
    category: "shoes",
    type: "Flats",
    rating: 4.5,
    stock: 90,
    gender: "women",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 3,
    title: "Long sleeve Jacket",
    description:
      "Add a touch of casual style to your wardrobe with these canvas flats. They are lightweight and comfortable for all-day wear. Available in various colors and sizes.",
    colors: ["#336600", "#993300"],
    imghover: "/images/img-hover2.jpg",
    img: "images/img2.jpg",
    images: ["/images/img1.jpg", "/images/img2.jpg", "/images/img3.jpg"],
    company: "CasualChic",
    price: 200,
    oldprice: 220,
    category: "clothes",
    type: "Flats",
    rating: 4.5,
    stock: 90,
    gender: "women",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 4,
    title: "Long sleeve Jacket",
    description:
      "Add a touch of casual style to your wardrobe with these canvas flats. They are lightweight and comfortable for all-day wear. Available in various colors and sizes.",
    colors: ["#336600", "#993300"],
    imghover: "/images/img-hover3.jpg",
    img: "images/img3.jpg",
    images: ["/images/img1.jpg", "/images/img2.jpg", "/images/img3.jpg"],
    company: "CasualChic",
    price: 200,
    oldprice: 220,
    category: "accessories",
    type: "Flats",
    rating: 4.5,
    stock: 90,
    gender: "women",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 5,
    title: "Long sleeve Jacket",
    description:
      "Add a touch of casual style to your wardrobe with these canvas flats. They are lightweight and comfortable for all-day wear. Available in various colors and sizes.",
    colors: ["#336600", "#993300"],
    imghover: "/images/img-hover1.jpg",
    img: "images/img7.jpg",
    images: ["/images/img7.jpg", "/images/img2.jpg", "/images/img3.jpg"],
    company: "CasualChic",
    price: 200,
    oldprice: 220,
    category: "shoes",
    type: "Flats",
    rating: 4.5,
    stock: 90,
    gender: "women",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 6,
    title: "Long sleeve Jacket",
    description:
      "Add a touch of casual style to your wardrobe with these canvas flats. They are lightweight and comfortable for all-day wear. Available in various colors and sizes.",
    colors: ["#336600", "#993300"],
    imghover: "/images/img-hover8.jpg",
    img: "images/img8.jpg",
    images: ["/images/img1.jpg", "/images/img2.jpg", "/images/img3.jpg"],
    company: "CasualChic",
    price: 200,
    oldprice: 220,
    category: "clothes",
    type: "Flats",
    rating: 4.5,
    stock: 90,
    gender: "women",
    size: ["S", "M", "L", "XL"],
  },
];
