import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import GoTop from "@/components/Layout/GoTop";
import "./globals.css";
import type { Metadata } from "next";
import StyledJsxRegistry from "@/components/Provider";

export const metadata: Metadata = {
  title: "Drip-Associates - React Next eCommerce Templates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledJsxRegistry>
          <Navbar />
          {children}
          <Footer />
          <GoTop />
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
