import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import GoTop from "@/components/Layout/GoTop";
import "./globals.css";
import type { Metadata } from "next";
import StyledJsxRegistry from "@/components/Provider";

export const metadata: Metadata = {
  title: "Drip-Associate - React Next eCommerce Templates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // useEffect(() => {
  //   if (typeof window !== "undefined") {
  //     require("bootstrap/dist/js/bootstrap.min.js");
  //   }
  // }, []);

  return (
    <html lang="en">
      <body>
        <StyledJsxRegistry>
          <Navbar />
          {children}
          <Footer />
          <GoTop />
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
