import Footer from "@/components/Layout/Footer";
import GoTop from "@/components/Layout/GoTop";
import "./globals.css";
import type { Metadata } from "next";
import LayoutProvider from "@/components/Provider";
import Navbar from "@/components/Layout/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Drip-Associates - React Next eCommerce Templates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutProvider>
          <Navbar />
          {children}
          <Footer />
          <GoTop />
          <ToastContainer position="top-right" autoClose={3000} />
        </LayoutProvider>
      </body>
    </html>
  );
}
